services:
  - type: web
    name: Assistly-AI
    env: python
    pythonVersion: 3.10.13
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --only-binary=:all: tiktoken
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
